# Generated by Django 3.0.5 on 2020-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
