# Generated by Django 3.0.5 on 2020-04-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0002_pin_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='img',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
