# Generated by Django 3.0.5 on 2020-05-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0011_auto_20200515_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='lat',
            field=models.TextField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='lng',
            field=models.TextField(verbose_name='Долгота'),
        ),
    ]
