# Generated by Django 3.0.5 on 2020-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0017_auto_20200612_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
