# Generated by Django 3.0.5 on 2020-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0018_auto_20200612_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
