# Generated by Django 3.0.5 on 2020-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0022_auto_20200615_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Статус нарушения')),
            ],
        ),
    ]
