# Generated by Django 3.0.5 on 2020-06-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0024_auto_20200627_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='status_pin',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='Pin.StatusPin'),
            preserve_default=False,
        ),
    ]
