# Generated by Django 3.0.5 on 2020-09-06 10:58

from django.db import migrations, models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0027_pin_status_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, storage=storages.backends.dropbox.DropBoxStorage(), upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='pin',
            name='img',
        ),
        migrations.AddField(
            model_name='pin',
            name='img',
            field=models.ManyToManyField(to='Pin.Images'),
        ),
    ]
