# Generated by Django 3.0.5 on 2020-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pin', '0028_auto_20200906_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crowdfunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название')),
                ('want', models.FloatField()),
                ('have', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Название картинки'),
            preserve_default=False,
        ),
    ]
